import OpenAI from 'openai';
import { zodResponseFormat } from 'openai/helpers/zod';
import { z } from 'zod';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

const supabase = createClient(supabaseUrl, supabaseKey);

const QuestionSchema = z.object({
  question: z.string(),
  answer_choices: z.array(z.string()),
  answer: z.string(),
  explanation: z.string(),
});

const SectionSchema = z.object({
  questions: z.array(QuestionSchema),
});

export const generateSection = async (sectionName: string, sectionType: string) => {
  console.log(`generating a ${sectionType} section`);
  const prompt = `Generate a ${sectionType} SAT question section with questions, answers, and explanations that address each choice. Return in json format. I need these fields: question, answer_choices, answer, explanation. Answer_choices should be an array of strings, others should be string`;

  const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
  });

  // Call OpenAI API
  const completion = await openai.beta.chat.completions.parse({
    model: "gpt-4o-mini-2024-07-18",
    messages: [{ role: "user", content: prompt }],
    response_format: zodResponseFormat(SectionSchema, "section"),
  });

  const generatedText = completion.choices[0].message.parsed;
  if (!generatedText) {
    throw new Error('No content generated by OpenAI');
  }

  // Create a new section
  const { data: sectionData, error: sectionError } = await supabase
    .from('sections')
    .insert([
      { name: sectionName, section_type: sectionType }  // Assuming sectionName is the type of the section
    ])
    .select('id')
    .single();

  if (sectionError) {
    throw new Error("Error in setting section: " + sectionError.message);
  }

  const sectionId = sectionData.id;

  // Parse generatedText.questions into an array
  const questions = generatedText.questions;

  // Store each question and answer in Supabase
  for (const question of questions) {
    const { error: questionError } = await supabase
      .from('questions')
      .insert([
        { 
          section_id: sectionId,  // Use the newly created section ID
          question: question.question,
          answer_choices: question.answer_choices,
          answer: question.answer,
          explanation: question.explanation
        }
      ]);

    if (questionError) {
      throw new Error("Error in setting question: " + questionError.message);
    }
  }

  return { answer: generatedText, sectionId: sectionId };
};