// General UI Text
export const GENERATING = 'Generating';
export const SUBMITTING = 'Submitting...';
export const SUBMIT = 'Submit';
export const NEXT_QUESTION = 'Next';
export const PREVIOUS_QUESTION = 'Previous';
export const TAKE_AGAIN = 'Take Again';
export const SHOW_EXPLANATION = 'Show Explanation';
export const HIDE_EXPLANATION = 'Hide Explanation';
export const NO_EXPLANATION = 'No explanation available.';
export const LOADING = 'Loading...';
export const VIEW_YOUR_PROGRESS = 'View Your Progress';
export const CATEGORY_PERFORMANCE = 'Category Performance';
export const DETAILED_REVIEW = 'Detailed Review';
export const OTHER_CATEGORY = 'Other';

// Page Titles & Headers
export const WELCOME = 'Welcome!';
export const YOUR_PROGRESS = 'Your Progress';
export const CATEGORY_PERFORMANCE_TITLE = 'Category Performance';
export const NO_SECTION_SELECTED_TITLE = 'No section selected';
export const QUESTION_REVIEW_TITLE = 'Question Review';

// Sidebar & Section Related
export const SIDEBAR_QUESTION_SKIP_INFO =
  'When you skip a question, it will appear here.';
export const NEW_MATH_SECTION = 'New Math Section';
export const NEW_READING_SECTION = 'New Reading Section';

// Math Categories
export const ALGEBRA = 'Algebra';
export const ADVANCED_MATH = 'Advanced Math';
export const PROBLEM_SOLVING_DATA_ANALYSIS =
  'Problem-Solving and Data Analysis';
export const GEOMETRY_TRIGONOMETRY = 'Geometry and Trigonometry';

// Reading Categories
export const INFO_IDEAS = 'Information and Ideas';
export const CRAFT_STRUCTURE = 'Craft and Structure';
export const EXPRESSION_IDEAS = 'Expression of Ideas';
export const STANDARD_ENGLISH_CONVENTIONS = 'Standard English Conventions';

// Button & Prompts
export const WELCOME_PROMPT =
  'Click a section in the sidebar or generate a new one to get started practicing.';
export const NO_SECTION_SELECTED_PROMPT =
  'Please select a section to review from the sidebar.';

// Error Messages
export const ERROR_FETCHING_SECTIONS = 'Error fetching sections';
export const ERROR_FETCHING_SECTION = 'Error fetching section';
export const ERROR_FETCHING_RESULTS = 'Error fetching results';
export const ERROR_FETCHING_QUESTIONS = 'Error fetching questions';
export const ERROR_FETCHING_ANSWERS = 'Error fetching answers';
export const ERROR_CHECKING_ANSWERS = 'Error checking for existing answer';
export const ERROR_UPDATING_ANSWER = 'Error updating answer';
export const ERROR_INSERTING_ANSWER = 'Error inserting answer';
export const ERROR_SUBMITTING_ANSWERS = 'Failed to submit answers';
export const ERROR_CREATING_SECTION_API = 'Failed to create section via API';
export const ERROR_SETTING_SECTION_DB = 'Error in setting section';
export const ERROR_SETTING_QUESTION_DB = 'Error in setting question';
export const ERROR_NO_OPENAI_CONTENT = 'No content generated by OpenAI';
export const ERROR_UNKNOWN = 'Unknown error';
export const ERROR_MISSING_FIELDS = 'Missing required fields';
export const ERROR_SECTION_ID_NULL =
  'Error: sectionId is unexpectedly null after creation.';

// OpenAI Prompt Instructions
export const OPENAI_RESPONSE_FORMAT_INSTRUCTIONS = `Return in json format. I need these fields: section_title (string), questions (array).`;
export const OPENAI_QUESTION_FORMAT_INSTRUCTIONS = `For each question, provide: question (string), answer_choices (array of strings), answer (string), explanation (string).`;
export const OPENAI_PASSAGE_INSTRUCTIONS = `Reading questions that refer to a passage should include the passage in the question field.`;
export const OPENAI_TITLE_INSTRUCTIONS = `Include a short, relevant title for the section. The title should be loosely based on the concepts tested in the section but not too esoteric - keep it short, general, but relevant to the concepts.`;
